# Generated by Django 5.0.7 on 2024-07-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
