# Generated by Django 5.0.7 on 2024-07-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
