# Generated by Django 5.0.4 on 2024-08-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('working_period', models.CharField(max_length=100)),
                ('tasks', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
    ]
